### Get Users
GET http://localhost:3001/users

### Create New User
POST http://localhost:3001/users/new
Content-Type: application/json

{
    "username": "DannyG",
    "password": "dgpass"
}

### Get Specific User by userID
GET http://localhost:3001/users/643d748676ae031424fa88a4

### GET Recipes by userID
GET http://localhost:3001/users/64361d7cd55f42890bfc8408/recipes

### Add New Recipe to User 
POST http://localhost:3001/users/643ea90ca8e79a1a38612acf/recipes/new
Content-Type: application/json

{
    "dishName": "Kodiak Pancakes",
    "servingSize": "1",
    "ingredients": ["Kodiak Mix", "Water", "Frozen Fruit"],
    "directions": ["Mix Water and Pancake Mix", "pour onto skilled", "cook and enjoy"],
    "imageURL": "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee.png"
}

### Delete Recipe from User 
DELETE  http://localhost:3001/users/64361c5ae5079b3014302b8f/recipes/delete/643622a43c73fddf844a1446

### Get Recipes
GET http://localhost:3001/recipes
